import { execFile } from "node:child_process";
import { promisify } from "node:util";
import type { Plan, UnresolvedFinding } from "@harness/agents";
import type { GateRunSummary } from "@harness/core";
import type { UnitResult } from "./unit.ts";

const execFileAsync = promisify(execFile);

export interface PullRequestInput {
  worktree: string;
  branch: string;
  baseBranch: string;
  draft: boolean;
  title: string;
  body: string;
}

/**
 * Everything a reviewer needs to decide whether to trust the change, in the one
 * place they will actually look.
 *
 * Unresolved findings are stated first and in full. A pipeline that buries what
 * its own reviewers could not settle trains people to merge without reading,
 * which removes the only remaining human check.
 */
export function buildPrBody(options: {
  task: string;
  runId: string;
  plan: Plan;
  units: UnitResult[];
  integrationGates: GateRunSummary | null;
  unresolved: UnresolvedFinding[];
  conflictedUnits: string[];
  costUsd: number;
}): string {
  const { plan, units, unresolved, integrationGates } = options;
  const lines: string[] = [];

  lines.push("## Task", "", options.task, "", "## Approach", "", plan.summary, "");

  if (unresolved.length > 0) {
    lines.push(
      `## Unresolved review findings (${unresolved.length})`,
      "",
      "The adversarial reviewer raised these and they were not settled within the",
      "round budget. Each is either a real defect or a reviewer error — the pipeline",
      "could not determine which, so a human must.",
      "",
    );
    for (const finding of unresolved) {
      const where = finding.file ? ` \`${finding.file}${finding.line ? `:${finding.line}` : ""}\`` : "";
      lines.push(
        `- **${finding.severity}** (${finding.unitId}, round ${finding.round})${where} — ${finding.claim}`,
        `  - Reproduction: ${finding.reproduction}`,
        `  - ${finding.verifiedByExecution ? "Reviewer executed this." : "Not executed by the reviewer; may be wrong."}`,
      );
    }
    lines.push("");
  }

  lines.push(
    "## Units",
    "",
    "| Unit | Status | Review rounds | Findings raised | Unresolved |",
    "|---|---|---|---|---|",
  );
  for (const unit of units) {
    const raised = unit.reviews.reduce((sum, review) => sum + review.findings.length, 0);
    lines.push(
      `| ${unit.title} (\`${unit.unitId}\`) | ${unit.status} | ${unit.reviews.length} | ${raised} | ${unit.unresolved.length} |`,
    );
  }
  lines.push("");

  if (plan.constraints.length > 0) {
    lines.push("## Design constraints", "", ...plan.constraints.map((c) => `- ${c}`), "");
  }
  if (plan.risks.length > 0) {
    lines.push("## Risks flagged at design time", "", ...plan.risks.map((r) => `- ${r}`), "");
  }
  if (options.conflictedUnits.length > 0) {
    lines.push(
      "## Merge conflicts resolved by the combiner",
      "",
      "These units overlapped despite disjoint planned ownership. Read the",
      "resolution closely — a conflict resolution that drops one side's behaviour",
      "does not fail any gate.",
      "",
      ...options.conflictedUnits.map((id) => `- \`${id}\``),
      "",
    );
  }

  lines.push("## Verification", "");
  if (integrationGates) {
    lines.push("| Gate | Status | Duration |", "|---|---|---|");
    for (const gate of integrationGates.results) {
      lines.push(`| ${gate.label} | ${gate.status} | ${(gate.durationMs / 1000).toFixed(1)}s |`);
    }
  } else {
    lines.push("_No integration gate run recorded._");
  }

  lines.push(
    "",
    "---",
    "",
    `Run \`${options.runId}\` · cost $${options.costUsd.toFixed(4)} · generated by the harness pipeline.`,
    "Full transcripts, gate logs, and per-unit patches are under `.harness/runs/`.",
  );

  return lines.join("\n");
}

/** Create the pull request with `gh`. Returns the PR URL. */
export async function openPullRequest(input: PullRequestInput): Promise<string> {
  const args = [
    "pr",
    "create",
    "--base",
    input.baseBranch,
    "--head",
    input.branch,
    "--title",
    input.title,
    "--body",
    input.body,
  ];
  if (input.draft) args.push("--draft");

  const { stdout } = await execFileAsync("gh", args, {
    cwd: input.worktree,
    encoding: "utf8",
    maxBuffer: 8 * 1024 * 1024,
  });
  return stdout.trim().split("\n").pop() ?? "";
}

export async function ghAvailable(): Promise<boolean> {
  try {
    await execFileAsync("gh", ["auth", "status"], { encoding: "utf8" });
    return true;
  } catch {
    return false;
  }
}
